import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // 由 docs/ 目录结构 + 各篇 sidebar_position + 文件夹 _category_.json 生成整棵侧栏
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
